//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaothong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HangDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_HangDT()
        {
            this.KhoaHocs = new HashSet<KhoaHoc>();
            this.NguoiLX_HoSo = new HashSet<NguoiLX_HoSo>();
        }
    
        public string MaHangDT { get; set; }
        public string TenHangDT { get; set; }
        public string HangGPLX { get; set; }
        public string SoVBPL { get; set; }
        public Nullable<int> TuoiHV { get; set; }
        public Nullable<int> ThamNien { get; set; }
        public Nullable<int> KmLXAT { get; set; }
        public string DKSH { get; set; }
        public string MucTieuDT { get; set; }
        public string GhiChu { get; set; }
        public bool TrangThai { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgaySua { get; set; }
        public Nullable<int> ThoiGianDaoTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoaHoc> KhoaHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiLX_HoSo> NguoiLX_HoSo { get; set; }
    }
}
