//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaothong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InHangDoiGPLX
    {
        public string MaDK { get; set; }
        public string SoHoSo { get; set; }
        public string SoGPLX { get; set; }
        public string SoSeri { get; set; }
        public string HangGPLX { get; set; }
        public string AnhChanDung { get; set; }
        public string HoVaTen { get; set; }
        public string NgaySinh { get; set; }
        public string QuocTich { get; set; }
        public string NoiCuTru1 { get; set; }
        public string NoiCuTru2 { get; set; }
        public string TinhTP { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string NguoiKy { get; set; }
        public string NguoiKy_ChuVu { get; set; }
        public string AnhChuKy { get; set; }
        public string AnhConDau { get; set; }
        public string NgayHH { get; set; }
        public string NgayTT { get; set; }
        public string MoTaVN { get; set; }
        public string MoTaEN { get; set; }
        public string MaIn { get; set; }
        public string Verify { get; set; }
        public string VerifyKey { get; set; }
        public string TrangThaiIn { get; set; }
        public Nullable<System.DateTime> NgayIn { get; set; }
        public string NguoiIn { get; set; }
        public string MaHTCap { get; set; }
        public string MaDV { get; set; }
        public string MaLo { get; set; }
        public string MaNguoiKy { get; set; }
        public Nullable<System.DateTime> NgayTT_A1 { get; set; }
        public Nullable<System.DateTime> NgayTT_A2 { get; set; }
        public Nullable<System.DateTime> NgayTT_A3 { get; set; }
        public Nullable<System.DateTime> NgayTT_A4 { get; set; }
        public Nullable<System.DateTime> NgayTT_B1 { get; set; }
        public Nullable<System.DateTime> NgayTT_B2 { get; set; }
        public Nullable<System.DateTime> NgayTT_C { get; set; }
        public Nullable<System.DateTime> NgayTT_D { get; set; }
        public Nullable<System.DateTime> NgayTT_E { get; set; }
        public Nullable<System.DateTime> NgayTT_F { get; set; }
        public Nullable<System.DateTime> NgayTT_FB2 { get; set; }
        public Nullable<System.DateTime> NgayTT_FC { get; set; }
        public Nullable<System.DateTime> NgayTT_FD { get; set; }
        public Nullable<System.DateTime> NgayTT_FE { get; set; }
        public Nullable<int> TrangThaiDongBo { get; set; }
        public Nullable<System.DateTime> NgayBanGiao { get; set; }
        public string NguoiBanGiao { get; set; }
        public string NguoiNhan { get; set; }
        public Nullable<System.DateTime> NgayTT_B11 { get; set; }
        public Nullable<System.DateTime> NgayTT_B12 { get; set; }
        public Nullable<System.DateTime> NgayTT_B13 { get; set; }
        public Nullable<System.DateTime> NgayTT_B14 { get; set; }
        public Nullable<System.DateTime> NgayTT_B15 { get; set; }
        public Nullable<System.DateTime> NgayTT_A11 { get; set; }
    }
}
