//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaothong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoaHoc_GiaoVien
    {
        public string MaKH { get; set; }
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public string BienSoXe { get; set; }
        public string LoaiGV { get; set; }
        public Nullable<int> SoHV { get; set; }
        public System.DateTime NgayHL { get; set; }
        public System.DateTime NgayHetHL { get; set; }
        public string GhiChu { get; set; }
        public bool TrangThai { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgaySua { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual XETAPLAI XETAPLAI { get; set; }
    }
}
