//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaothong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichHoc
    {
        public long MaLichHoc { get; set; }
        public string MaKH { get; set; }
        public int Thang { get; set; }
        public int Tuan { get; set; }
        public System.DateTime TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
        public string GiaiDoan { get; set; }
        public string KiemTra { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
