//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaothong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiLXHS_KQSH
    {
        public string MaKySH { get; set; }
        public string SoBaoDanh { get; set; }
        public string LoaiSH { get; set; }
        public System.DateTime NgaySH { get; set; }
        public int DiemSH { get; set; }
        public int DiemToiDa { get; set; }
        public string SatHachVien { get; set; }
        public string NhanXetSHV { get; set; }
        public string GhiChu { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgaySua { get; set; }
        public bool VangSH { get; set; }
        public int DiemToiThieu { get; set; }
    }
}
