//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaothong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiLXHS_GiayTo
    {
        public int MaGT { get; set; }
        public string MaDK { get; set; }
        public string SoHoSo { get; set; }
        public string TenGT { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MADK2 { get; set; }
    
        public virtual NguoiLX_HoSo NguoiLX_HoSo { get; set; }
    }
}
